apiVersion: v1
kind: Service
metadata:
  namespace: journal
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: LoadBalancer
  selector:
    app: journal-nodeapp
  ports:
  - port: 3333
    targetPort: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: journal
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: haungi/journal-nodeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333
